---
- name: Analysis
  hosts: rhel7
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true

  vars:
    leapp_upgrade_type: satellite
    leapp_satellite_organization:
    leapp_satellite_activation_key_post_analysis:
    leapp_satellite_activation_key:
    # By default the analysis role will use:
    # analysis_repos_el7: rhel-7-server-extras-rpms
    # Optionally override the default analysis_repos_el7 to use the upstream copr leapp repository:
    # analysis_repos_el7: copr:copr.fedorainfracloud.org:group_oamg:leapp
    leapp_preupg_opts: --target 8.10
    leapp_answerfile: |
      [remove_pam_pkcs11_module_check]
      confirm = True
  tasks:
    - name: Generate preupgrade analysis report
      ansible.builtin.import_role:
        name: analysis
...
